### ISSUE TITLE
NOT CRITICAL!! Can't create inventory csv for past time periods

### ISSUE THREAD

**Issue by CanDKD** [uic-utah/uic-forms#21]
I just noticed this when I tried to run uic-forms 3.0.4 for a time period which ended in the past.  For example, FFY beginning in 2017 and 2Q. The 7520.##-##-#### and 7520-4.##-##-#### csv files are created but not the 7520-Inventory csv file.

Is this just something we shouldn't trying to do?  Is there an easy, EASY coding change that will allow us to do this?

The reason I tried this was to show Dusty Earley, my replacement, how to run the tool and submit the csv files to the UIC Data Application

**Comment by steveoh** [comment]
Does it error out or is the file just not produced?

**Comment by CanDKD** [comment]
It appears to error out but the command line interface closes before I can read it .  Also, the 7520-Inventory.csv is not produced.

**Comment by steveoh** [comment]
ok, i'll look into the crash as i can reproduce it on my end also.
